ubuntu/snapcraft-desktop-helpers

snapcraft.yaml

These are still needed until the non-namespaced version of snapcraft-parser is released.

Add back the original parts as well so older versions of snapcraft-parser works.

---

common/desktop-exports

On install, $SNAP_USER_DATA/.themes is created and points to
$SNAP/usr/share/themes. On upgrade $SNAP_USER_DATA is copied from the previous
dir (eg, 'x1') to the new version (eg, 'x2') such that $SNAP_USER_DATA/.themes
points to the previous version's $SNAP/usr/share/themes. There is logic to
account for this in common/desktop-exports and it tries to:
ln -sf $SNAP/usr/share/themes $SNAP_USER_DATA/.themes
Because $SNAP_USER_DATA/.themes is a valid symlink, it is dereferenced and
tries to create $SNAP/usr/share/themes/themes, which is of course a readonly
directly and fails with:
ln: failed to create symbolic link '.../x2/.themes/themes': Read-only file
system
The script should instead use '-n' so that $SNAP_USER_DATA/.themes is updated
as intended.

common/desktop-exports: don't dereference target symlink on upgrades

---

common/desktop-exports

common/desktop-exports: export MIR_CLIENT_PLATFORM_PATH so that Mir client can function.

Support for Mir

---

common/desktop-exports
snapcraft.yaml

This is a workaround for the lack of locale definitions in the core image
(https://launchpad.net/bugs/1576282).

Install all available locales and ensure that apps can locate them.

---

common/desktop-exports
glib-only/launcher-specific
gtk/launcher-specific

Move the export of GI_TYPELIB_PATH from glib and gtk to the common exports file. I found that I needed this in my Qt application, which calls a python tool that uses gi. Instead of slowly adding this to every launcher-specific file, it seems like a good time to set it in all scenarios.

Export GI_TYPELIB_PATH in all cases

---

common/desktop-exports

Exports the launcher ARCH so that wrapper scripts launched by the launcher
can reuse this value without recomputing it again

Export $SNAP_LAUNCHER_ARCH

---

snapcraft.yaml

This adds dependency on indicator-<toolkit> parts
to add support to desktop indicators with snap
support patches.
Parts are currently defined at:
- https://github.com/3v1n0/appindicators-snapcraft-parts
While examples of indicators for various toolkits are
- https://github.com/3v1n0/indicators-examples-snaps

snapcraft.yaml: add dependency on remote indicator parts

---

snapcraft.yaml

but doesn't include extra stage packages. The launcher is going to be useful for snaps
using the gnome runtime and those wanting more control on their depends.

Define a new 'gnome' helper which is similar to the gtk3

---

common/desktop-exports
common/init
glib-only/Makefile
glib-only/init
gtk/Makefile
gtk/init
gtk/launcher-specific
gtk/runtime-exports
qt/Makefile
qt/init
qt/launcher-specific
qt/runtime-exports
snapcraft.yaml

Simplify and use RUNTIME refactoring by adding snap-specific libs to runtime ones.
Do it on both GTK and Qt sides.
Change slightly the logic by allowing generic init/runtime/generic desktop/specific desktop override order.

Runtime refactor

---

common/desktop-exports

Allow snaps to override LOCPATH to point to a different location within the snap.

Tweak LOCPATH export to point to the snap root.

---

common/desktop-exports

This is a workaround for <a href='https://pad.lv/1656340'>LP: #1656340</a>

Create $XDG_RUNTIME_DIR if it not exists

---

common/desktop-exports

Specify MIR_SOCKET.
The libmirclient default of $XDG_RUNTIME_DIR/mir_socket is wrong in snappy, where XDG_RUNTIME_DIR = /run/user/ID/snap.SNAPNAME/.  But all Mir snaps want to instead connect to /run/user/ID/mir_socket (no snap namespace).  So we should hardcode that path instead.

Add MIR_SOCKET

---

qt/launcher-specific

When we're running on the unity8-session snap the systemd user session is run based on the user instance, not based on the graphical desktop. And this is what applications get their environment from. They do get a DISPLAY variable if they've requested a "unity7" or "x11" interface though, so we can key the backend based on that.

Switch to key backend based on the DISPLAY variable

---

common/desktop-exports

Sometimes we run in a kiosk mode with just one global mir server and no user servers like unity8.  So let's support apps that use desktop-launch even in that situation.
This now basically reproduces the default path logic internal to Mir itself, just using the snappy locations.

Support running directly on global mir servers too

---

gtk/runtime-exports
snapcraft.yaml

It was just called gnome before

snapcraft.yaml: add desktop-platform-gnome part

---

common/desktop-exports

This is required for text input to work in SDL2 games.
Ref: https://lists.ubuntu.com/archives/snapcraft/2017-January/002699.html.

Export XLOCALEDIR to give XOpenIM a chance to locate locale data.

---

common/desktop-exports

This PR updates LD_LIBRARY_PATH with the testability paths so that snaps can load the testability libraries and be introspected by autopilot. The testability libraries are provided by autopilot-qt snap using a content sharing interface

Adding support for testability

---

common/desktop-exports
snapcraft.yaml

So Mir support continues to evolve.  After some meetings, it's been determined that the mir-libs content snap is the only supported way of using Mir on snappy.  So let's point at it instead of u-a-p and set LD_LIBRARY_PATH accordingly.
I also skip including the Mir libs in consuming snaps without their knowledge.  It doesn't seem possible to avoid actually including the packages themselves (they are depends of gtk and qt), but we can easily avoid priming them.
See https://launchpad.net/bugs/1663048 for some context.

Support mir-libs content snap

---

qt/launcher-specific
snapcraft.yaml

This adds support to desktop indicators for snapped apps.

snapcraft.yaml: include libraries for indicators support

---

common/desktop-exports

We currently have a bit of code to set MIR_SOCKET=/run/mir_socket if the user session doesn't have a socket.  This was intended to support kiosk-style snaps that don't run a full user session and just talk to the system Mir server directly.
However, this breaks in a couple places.  If MIR_SOCKET is set, some toolkits (Qt at least) will prefer to use it.  And ubuntu-app-launch unconditionally sets it when launching through it.  So a couple problems:
- When launching in unity7 directly (/snap/bin/testsnap) and USC happened to be running, we were setting MIR_SOCKET=/run/mir_socket [1], Qt then tried to talk to USC, and nothing ever was drawn.
- When launching via UAL in unity7 (whether USC was running or not), MIR_SOCKET was set by UAL to /run/user/XXX/mir_socket, Qt then tried to talk to a …

Don't set MIR_SOCKET=/run/mir_socket when not in kiosk mode

---

common/desktop-exports

See discussion at:
https://forum.snapcraft.io/t/desktop-launch-causes-failed-to-create-symbolic-link/977/7

Don't symbolic link gtk_configs if they already exist

---

common/init
common/mark-and-exec

This ensures the desktop launchers can also be used with classic snaps.

Write the .last_revision stamp under $SNAP_USER_DATA.

---

common/desktop-exports

If detect wayland server socket, then set environment so applications prefer wayland, and setup compat symlink (until we use user mounts. Remember, XDG_RUNTIME_DIR is /run/user/<uid>/snap.$SNAP so look in the parent directory for the socket. For details: https://forum.snapcraft.io/t/wayland-dconf-and-xdg-runtime-dir/186/10
Note, this might not be how the desktop team wants to detect and use wayland, but it does work. Quoting from the forum:
"I have tested this with:
- an updated gnome-sudoko with gnome-3-24 platform snap that uses a symlink from $XDG_RUNTIME_DIR/wayland-0 to $XDG_RUNTIME_DIR/../wayland-0 on 17.10
- an updated gnome-sudoko with gnome-3-24 platform snap that uses a symlink from $XDG_RUNTIME_DIR/wayland-0 to $XDG_RUNTIME_DIR/../wayland-0 on 17.04
- an updated gnome-logs-udt …

prefer wayland if wayland detected and create compat symlink

---

common/init

When running the desktop-gnome-platform helper, it will exit part-way through if the platform interface isn't connected. Because the init part of the script is run before this then the needs_update/.last_revision will be set causing the helper to not compile the gnome schemas on the next launch, even if the platform interface is correctly connected. This causes gnome apps to die until either removed and reinstalled or an updated version is installed causing the .last_revision to no-longer match
this pr removes the setting of .last_revision in init deferring that to mark-and-exec.

update init to fix cases where the helper exits

---

demos/gtk3/snapcraft.yaml
snapcraft.yaml

See https://forum.snapcraft.io/t/the-desktop-interfaces/2042 for details.
demos/gtk3/snapcraft.yaml:
- remove x11 (already included with unity7)
- add desktop, desktop-legacy and wayland
snapcraft.yaml: rephrase and update for desktop, desktop-legacy and wayland

adjust for new desktop interfaces

---

common/desktop-exports
snapcraft.yaml

This fixes an issue with apps that use APIs such as  get_user_special_dir to get XDG_XXX_DIR locations.  This would be probably be better if we set XDG_XXX_DIR to directories of the host's homedir instead of in $SNAP_USER_DATA, however I don't see a way to get that dir.  I think this PR is a step in the right direction.

Ensure XDG_CONFIG_HOME is set and run xdg-user-dirs-update

---

common/desktop-exports

On Fedora $SNAP is under /var and there is some magic in snapd to map it to /snap.  We need to handle that case and reset $SNAP

Mangle $SNAP to work around path issues on Fedora

---

common/desktop-exports

This PR changes the way we get fontconfig to find the fonts provided by the snap.
Rather than symlinking the snap's fonts to `$XDG_DATA_HOME/fonts`, we instead write a config file to `$XDG_CONFIG_HOME/fontconfig/fonts.conf` that augments the fontconfig search path with the locations within the snap.
This has a few benefits:
1. if the app is using the GNOME platform snap, we can let it see fonts from the both the app snap and platform snap.
2. We can also point it at fonts in the user's home directory, fixing bug #85.
In addition to (2), I also provide access to the user's local fontconfig cache directory to avoid the need to scan fonts found there.  It doesn't seem worth trying to use caches from the snaps though, since the caches are keyed off paths and snap paths change with each …

common: write a user fonts.conf file rather than symlinking fonts into $XDG_DATA_HOME

---

common/desktop-exports

Currently desktop-launch builds caches for a number of things the first time a snapped app is run (gsettings schemas, mime database, icon theme caches, etc).  Some of these operations are quite expensive, so it would be nice to avoid it if possible.
This branch makes a number of changes towards this goal:
1. If a schema dir on $XDG_DATA_DIRS has a `gschemas.compiled` file, don't symlink its schemas to $XDG_DATA_HOME.  Further more, if we don't symlink any schemas, don't run glib-compile-schemas.
2. If a mime.cache file exists in the snap, don't copy the mime database or run update-mime-database.
3. If an icon theme has an icon-theme.cache file, don't symlink it $XDG_DATA_HOME or run update-icon-caches.
Of these, (2) is the most noticeable.  So that this actually does something, the …

Use caches from runtime if they exist

---

common/desktop-exports

This PR reverts one of the changes from #86: it prepends $XDG_DATA_HOME to $XDG_DATA_DIRS again.
According to the spec, this shouldn't be needed, but older versions of GLib (such as the one in Ubuntu 16.04) don't check for schemas in $XDG_DATA_HOME:
https://bugzilla.gnome.org/show_bug.cgi?id=741335
This didn't show up when testing with the gnome platform snap, since that contains a new enough version of GLib.

common: add $XDG_DATA_HOME back to $XDG_DATA_DIRS: it is needed for GSettings with old GLib

---

common/desktop-exports

by defining the DISABLE_WAYLAND environment variable.

Allow apps that don't support wayland natively to run on wayland through X11,

---

common/desktop-exports

Applications using libpulse (eg. Spotify, VLC) will probe
$XDG_RUNTIME_DIR/pulse/native as one of locations where PulseAudio socket may be
available.
In case of snaps, the XDG_RUNTIME_DIR is set to /run/user/$(id -u)/snap.<snap>.
If PulseAudio has a socket in the original $XDG_RUNTIME_DIR, make sure that it's
also available in snap-specific one.

common/desktop-exports: make PulseAudio socket available in snap-specific XDG_RUNTIME_DIR

---

common/desktop-exports

This issue is there for too long time, by defining `XCURSOR_PATH` to proper folder, we can use installed cursor themes to match system, instead of the default ugly X11 cursors.
To test this you can just try it on already available snaps by doing something like:
`snap=spotify; env XCURSOR_PATH=/snap/$snap/current/usr/share/icons snap run $snap`

Set XCURSOR_PATH to proper folder to use properly themed pointer cursors

---

common/desktop-exports

Create links to xdg user dirs under the snap's $HOME instead of expecting it under $SNAP_USER_DATA.  This fixes linking the appropriate directory regardless of the snap having $HOME set to $SNAP_USER_DATA or $SNAP_USER_COMMON.

Create links to xdg user dirs under the snap's $HOME

---

common/desktop-exports

This will ensure that non-essential cached files are not copied back and forth upon {up,down}grade of snaps.

Move XDG_CACHE_HOME to $SNAP_USER_COMMON/.cache.

---

common/desktop-exports

User home could be somewhere else (although snapd doesn't properly support this yet), but we should be prepared a that case.

desktop-exports: use $REALHOME everywhere

---

common/desktop-exports
common/init
gtk/launcher-specific
snapcraft.yaml

The desktop interface actually gives us access to the users $XDG_CONFIG_HOME/user-dirs.*, so we should link those into the snap's $XDG_CONFIG_HOME to get the proper user-dirs.

If the user-dirs.* exists in the $REALHOME, link them into the snap's XDG_CONFIG_HOME.

---

src/bindtextdomain.c

Always free snap_locale_path, and null freed variables to avoid double-free corruption.

---

common/desktop-exports

Pointing fontconfig to the snapped fonts.conf file fails as the paths in the snapped file have not been edited to suit the snapped directory layout. This causes crashes in chromium/electron based apps for me.

Fix FONTCONFIG_PATH to point to where we generate fonts.conf

---

common/desktop-exports

Snapd can expose EGL vendor directory on glvnd enabled nvidia based systems .
Make sure to advertise the location through `__EGL_VENDOR_LIBRARY_DIRS` so that
glvnd runtime can properly locate vendor files.
Related snapd forum topic: https://forum.snapcraft.io/t/nvidia-gl-libs-access-broken-on-ubuntu-18-04/4440/31?u=mborzecki

common/desktop-exports: include EGL vendor dir on glvnd enabled systems

---

common/desktop-exports

Previously the script relies on the behavior of `test`(builtin) when 1 arguments is given(returns 0 when argument string not null, 1 elsewise), which is unnecessary and error-prone when the command path contains spaces.  This patch replaces them with straight-forward return value checking of `command`(also builtin).
Maybe-related-to: desktop-launch: line 199: [: too many arguments · Issue #114 · ubuntu/snapcraft-desktop-helpers <https://github.com/ubuntu/snapcraft-desktop-helpers/issues/114>

desktop-exports: Improve command detection method

---

common/desktop-exports

This handles themes mounted under $SNAP/data-dir which is desirable over $SNAP/usr/share which may not be empty

Prepend $SNAP/data-dir to XDG_DATA_DIRS to allow mounting themes there

---

common/init
common/mark-and-exec

Specifically, this outputs elapsed time for now, but we could introduce further debug output.

Output some profiling information when $SNAP_DESKTOP_DEBUG is set

---

common/desktop-exports

This PR reverts #115, which was the cause of applications regenerating all fontconfig cache files on first run.
The `fonts.conf` generated by desktop-launch is not a complete fontconfig configuration, but instead intended to be included by the main `${RUNTIME}/etc/fonts/fonts.conf` file.  Among other things, main `fonts.conf` file adds `/var/cache/fontconfig` as a cache directory: without that, the confined app can not take advantage of the host system caches.
This PR should also bring back the all the font aliases that applications depend on for correct font selection.
The purpose of PR #115 from @gerboland was to fix some problem with some Electron apps on Ubuntu Core systems, so this will probably reintroduce whatever problem that was.  On balance I think reversion is the right choice …

Revert change to FONTCONFIG_FILE, so we have a complete fontconfig configuration

---

common/desktop-exports
gtk/launcher-specific
qt/launcher-specific

Fix Wayland support when using Qt5, and print a warning when trying to use Wayland with toolkits that do not support it

Move toolkit-specific decisions out of common

---

snapcraft.yaml

Avoid `make: gcc: Command not found` error when the including snap
doesn't require a GCC toolchain by itself.
Fixes #146.
Refer-to: gtk3 part doesn't install gcc · Issue #146 ·
ubuntu/snapcraft-desktop-helpers
<https://github.com/ubuntu/snapcraft-desktop-helpers/issues/146>

List build-essential as one of the `build-packages` for gtk parts

---

common/desktop-exports

I noticed my failing GUI snaps on Core were doing this:
[pid 18922] access("/snap/gtk3-example/x1/etc/fonts/conf.d/conf.d", R_OK) = -1 ENOENT (No such file or directory)
which suggested the FONTCONFIG_PATH was incorrectly including "conf.d". This patch fixes my font loading issues, and doesn't break any desktop snap fonts I've tried.

Set FONTCONFIG_PATH correctly to fix loading in-snap fonts

---

glib-only/Makefile
gtk/Makefile
qt/Makefile

Fixes #148.
Refer-to: Docker build breaks when snap repo path contains spaces ·
Issue #148 · ubuntu/snapcraft-desktop-helpers <https://github.com/ubuntu/snapcraft-desktop-helpers/issues/148

Quote all DESTDIR expansions for paths contain spaces

---

common/desktop-exports

Create it if it doesn't exist, otherwise next operations will fail
I was just running a snap, while I noticed:
```
marco@tricky:/data/telegram-snap (master):✓ $ mailspring 
/snap/mailspring/216/bin/desktop-launch: line 177: /home/marco/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/marco/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/marco/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/marco/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
```

desktop-exports: ensure we have $HOME/.config dir

---

snapcraft.yaml

Avoid `make: gcc: Command not found` error when the including snap doesn't require a GCC toolchain by itself.

List build-essential as one of the `build-packages` for qt parts (#141)

---

common/desktop-exports

Use `theme` variable instead of `i` in the inner themes cycles, fixing iterating error.
Also properly quote variables.

desktop-exports: don't break cycle overriding variables

---

gtk/launcher-specific
qt/launcher-specific

When working on a demo of a snap using the gtk2-common-themes snap, I needed to set `GTK_PATH` to point at the engines provided by that package.  However, the desktop-launch script turns around and resets it on us.
This branch modifies the GTK and Qt scripts to use the `append_dir` helper defined in `common/desktop-exports` to update the variable instead.

gtk, qt: use append_dir to modify GTK_PATH

---

common/desktop-exports
snapcraft.yaml

If the themes dir from gtk-common-themes is mounted, create links based on it rather than bundled themes.  This fixes snaps using parts other than desktop-gnome-platform that also use the content interfaces provided by gtk-common-themes

Link themes from data-dir when it's mounted

---

common/desktop-exports
common/init

Various fixes on `user-dirs`, see each commit description for more clarity.
However, the main issue addressed here is making sure that `user-dirs.*`are inside `$XDG_CONFIG_HOME` and not in `$HOME/.config` as those two paths might not match when the snap doesn't have `HOME=$SNAP_USER_DATA` (quite common when using `$SNAP_USER_COMMON` as `HOME`) as in that case the file is created in both locations and the one inside `XDG_CONFIG_HOME` (with not-fixed values) takes the priority.
Also improved the cases for snaps with desktop interface but without home readability (so that now linking to paths on real home happens again), and improved dirs and files migrations and dirs definitions updates.

desktop-exports: Fixes and improvements for XDG dirs generations

---

common/desktop-exports

Note that this usually requires additional stage packages containing the drivers (i965-va-driver-shaders / mesa-va-drivers).

Tell libva where to find the drivers.

---

common/init

ppc64el arch has a special debian multiarch name and requires special casing, check out https://wiki.debian.org/Multiarch/Tuples for more info

Fix ppc64el arch compatibility

---

qt/launcher-specific

It doesn't allow colons, as it's checking for the directory to be one.

[qt] fix prepend_dir usage

---

gtk/runtime-exports

The patch parses the actual providing snap name from $SNAP/meta/snap.yaml.
```
$ my-awesome-app 
You need to connect this snap to the gnome platform snap.
You can do this with those commands:
snap install gnome-3-28-1804
snap connect my-awesome-app:gnome-3-28-1804 gnome-3-28-1804
```
Fixes #178.

Make the launcher print the actual gnome runtime snap the user is required to install and connect

---

qt/launcher-specific

This allows gtk-common-themes integration, which requires QT_QPA_PLATFORMTHEME=gtk
Fixes #180 

Only set QT_QPA_PLATFORMTHEME to appmenu-qt5 if it is not set by other value (or unset)

---

snapcraft.yaml

Only gcc package is required to build the bindtextdomain preload
library, the rest are redundant and make Snapcraft install a lot of
useless packages.

gnome-platform: Drop unnecessary build-packages

---

src/bindtextdomain.c

This is the folder snapcraft will build into by default, and should be searched first.
Tested on a simple built-from-source zenity dialog, the I18N now works.

bindtextdomain: Support locale files under share/locale

---

qt/launcher-specific

Fix Qt Web Engine application by setting the proper
QTWEBENGINEPROCESS_PATH.
Fixes #186.

qt: Fix locating QtWebEngineProcess executable

---

common/desktop-exports
common/init

Fixes adapted from @galgalesh 
* speed up desktop-launch by not calling mkdir -p
* skip icon cache creation for theme and runtime snaps

Performance improvements backported from snapcraft extension

---

snapcraft.yaml

8565db1e8be77e03e3dc483a42f9adde8654234d added audio-playback to the
snapcraft template. Now that audio-playback has been available in
several snapd releases and snapd 2.43 and later only manually connects
pulseaudio, removed pulseaudio from the template, leaving
audio-playback.

snapcraft.yaml: remove pulseaudio from template

---

common/desktop-exports

The absence of the cache file (after manual deletion) was causing the chromium snap to crash when opening a GTK file dialog.

Regenerate the GDK pixbuf loaders cache file if for whatever reason it isn't there (LP: #1863801).

---

common/desktop-exports
common/init

fixes https://github.com/ubuntu/snapcraft-desktop-helpers/issues/173
this is a port of https://github.com/snapcore/snapcraft/pull/2930
This reduces hot run time for `desktop-launch` on *affected systems*. Depending on the snap, this can remove 1 - 10 seconds off its hot start time.
`desktop-launch` keeps needlessly setting `needs_xdg_reload=true` when `~/.config/user-dirs.dirs` exist but `~/.config/user-dirs.locale` doesn't. This happens when a user gets the `xdg-user-dirs-gtk` dialog (after changing the system language) and checks the "Don't ask me this again" option, which removes `~/.config/user-dirs.locale` .
This patch makes sure we only set `needs_xdg_reload=true` when something actually changes and removes the hash of `~/.config/user-dirs.locale` when the file itself is removed. …

Handle case when only user-dirs.locale doesn't exist

---

common/desktop-exports

This allows libglvnd to find Mesa's EGL implementation and fixes things that rely on EGL under Wayland like SDL2 and Qt 5.
Fixes #172 
Also reported downstream: https://github.com/maxiberta/moonlight-snap/issues/7

common/desktop-exports: include EGL vendor dir for Mesa

---

common/desktop-exports

The problem with `__EGL_VENDOR_LIBRARY_DIRS` is that the first one that has _any_ configuration (e.g. [`50_mesa.json`](https://packages.ubuntu.com/search?searchon=contents&keywords=50_mesa.json&mode=exactfilename&suite=focal&arch=any)) will be picked up, even if further dirs have higher priority ones (e.g. [`10_nvidia.json`](https://packages.ubuntu.com/search?searchon=contents&keywords=10_nvidia.json&mode=exactfilename&suite=focal&arch=any).
`snapd` only puts stuff in `/var/lib/snapd/lib/gl{,vnd}` on systems with Nvidia, so snaps that use GL ship the Mesa stack "as a fallback". But it's the system one that should be picked up first.
More context:
https://github.com/NVIDIA/libglvnd/blob/master/src/EGL/icd_enumeration.md

Prepend GL paths rather than appending

---

common/desktop-exports

When a user has one or several `XDG_SPECIAL_DIRS` folders symlinked in their real home folder to elsewhere in their real home folder `common/desktop-exports` will attempt to mv those folders to themselves.
* guard `mv` calls with test for `is_subpath` to ensure that we're only moving symlinks we created.
While this is not a fatal error here, the electron-builder copies are using `bash -e` so they fail hard. I will forward these changes to electron-builder once reviewed here... (currently symlinks for Documents etc, combined with the electron-builder default of plugging `home`, cause electron-builder-built snaps to refuse to launch because the `mv` calls break the execution due to `bash -e`.)
Signed-off-by: Daniel Llewellyn <diddledan@ubuntu.com>

Fix Documents, Pictures, Music etc are symlinks in

---

common/desktop-exports

I've been working on the snap of FFmpeg and OBS Studio and noticed that VDPAU is not working correctly. This pull request sets  `VDPAU_DRIVER_PATH` appropriately and supports NVIDIA hardware when the host has the proprietary drivers installed.

Set VDPAU_DRIVER_PATH appropriately

---

README.md

Doesn't seem to be available anymore, remove it to stop it from confusing people any further.

Remove Rocketchat reference

---

common/desktop-exports

Signed-off-by: Salem Yaslem <s@sy.sa>
I discuses about this issue on Snapcraft forum: 
https://forum.snapcraft.io/t/snap-package-cannot-read-fonts-conf/

fix font render for modified fonts
